# Generated by Django 5.1.3 on 2024-11-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereço',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=200)),
                ('cep', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=15)),
            ],
        ),
    ]
