# Generated by Django 5.1.3 on 2024-11-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_endereço'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereço',
            name='nome',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
