# Generated by Django 5.1.3 on 2024-11-19 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_endereço_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereço',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.cliente'),
            preserve_default=False,
        ),
    ]
